/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PipelineIndexRouteImport } from './routes/pipeline/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as ActivitiesIndexRouteImport } from './routes/activities/index'
import { Route as PipelineIdRouteImport } from './routes/pipeline/$id'
import { Route as CustomersIdRouteImport } from './routes/customers/$id'
import { Route as ActivitiesIdRouteImport } from './routes/activities/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineIndexRoute = PipelineIndexRouteImport.update({
  id: '/pipeline/',
  path: '/pipeline/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIndexRoute = ActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineIdRoute = PipelineIdRouteImport.update({
  id: '/pipeline/$id',
  path: '/pipeline/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIdRoute = ActivitiesIdRouteImport.update({
  id: '/activities/$id',
  path: '/activities/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities/$id': typeof ActivitiesIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/pipeline/$id': typeof PipelineIdRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/pipeline/': typeof PipelineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities/$id': typeof ActivitiesIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/pipeline/$id': typeof PipelineIdRoute
  '/activities': typeof ActivitiesIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/pipeline': typeof PipelineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities/$id': typeof ActivitiesIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/pipeline/$id': typeof PipelineIdRoute
  '/activities/': typeof ActivitiesIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/pipeline/': typeof PipelineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities/$id'
    | '/customers/$id'
    | '/pipeline/$id'
    | '/activities/'
    | '/customers/'
    | '/pipeline/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities/$id'
    | '/customers/$id'
    | '/pipeline/$id'
    | '/activities'
    | '/customers'
    | '/pipeline'
  id:
    | '__root__'
    | '/'
    | '/activities/$id'
    | '/customers/$id'
    | '/pipeline/$id'
    | '/activities/'
    | '/customers/'
    | '/pipeline/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesIdRoute: typeof ActivitiesIdRoute
  CustomersIdRoute: typeof CustomersIdRoute
  PipelineIdRoute: typeof PipelineIdRoute
  ActivitiesIndexRoute: typeof ActivitiesIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  PipelineIndexRoute: typeof PipelineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/': {
      id: '/pipeline/'
      path: '/pipeline'
      fullPath: '/pipeline/'
      preLoaderRoute: typeof PipelineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/': {
      id: '/activities/'
      path: '/activities'
      fullPath: '/activities/'
      preLoaderRoute: typeof ActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/$id': {
      id: '/pipeline/$id'
      path: '/pipeline/$id'
      fullPath: '/pipeline/$id'
      preLoaderRoute: typeof PipelineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$id': {
      id: '/activities/$id'
      path: '/activities/$id'
      fullPath: '/activities/$id'
      preLoaderRoute: typeof ActivitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesIdRoute: ActivitiesIdRoute,
  CustomersIdRoute: CustomersIdRoute,
  PipelineIdRoute: PipelineIdRoute,
  ActivitiesIndexRoute: ActivitiesIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  PipelineIndexRoute: PipelineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
